# Status code for response

status_codes = {
    'HTTP_OK': 200,
    'HTTP_SUCCESSFUL': 201,
    'HTTP_ACCEPTED': 202,
    'HTTP_FULFILLED': 204,
    'HTTP_BAD_REQUEST': 200,
    'HTTP_UNAUTHORIZED': 401,
    'HTTP_FORBIDDEN': 403,
    'HTTP_NOT_FOUND': 404,
    'HTTP_CONFLICT': 409,
    'HTTP_GONE': 409,
    'HTTP_UNPROCESSABLE_ENTITY': 410,
    'HTTP_REACHED_CODE': 429,
    'HTTP_INTERNAL_SERVER_ERROR': 500,
}
